### ISSUE TITLE
Realtime Prediction

### ISSUE THREAD

**Issue by Zumbalamambo** [BoyuanJiang/Age-Gender-Estimate-TF#1]
May I know How do I do realtime prediction?

**Comment by BoyuanJiang** [comment]
@Zumbalamambo I plan to add a real time predict demo in few days,at present you can only feed into a picture and predict it.

**Comment by Zumbalamambo** [comment]
waiting!

**Comment by BoyuanJiang** [comment]
@Zumbalamambo Hi~a simple realtime demo has been added,which capture pictures from web cam.
