### ISSUE TITLE
20 year old baby

### ISSUE THREAD

**Issue by bobmoff** [BoyuanJiang/Age-Gender-Estimate-TF#36]
Hi,

Just managed to this project running and my first tries was very disappointing. Tried 3 photos of a child in the age of 1-3 years. All predictions landed on 15-20 years old. The most obvious one is the one where she is 1 year old, and predicted to be 20.

![20_year_old_baby](https://user-images.githubusercontent.com/1033236/58792214-05f57e80-85f4-11e9-90f0-82bd300342d7.png)

Could there be something in the way I installed the depencies or something else that is making the predictions so wrong ? I dont get any errors.

**Comment by sebastiaopamplona** [comment]
![dataset_dist](https://user-images.githubusercontent.com/27507750/68204107-32f0f780-ffbf-11e9-96c2-04fa2a36a632.png)
Hello bobmoff, the dataset that was used to train the model does not have many babies... So that it why it can't predict a baby's age very well.

**Comment by bobmoff** [comment]
ok, thx for taking the time to answer
