### ISSUE TITLE
Error while running convert_to_records.py

### ISSUE THREAD

**Issue by 0x1q** [BoyuanJiang/Age-Gender-Estimate-TF#6]
Hey there.
I love your program, it's very, very nice.
But i am getting this error, maybe you can help me?

`Askes-MBP:DareToAGE aske$ python convert_to_records_multiCPU.py --imdb --nworks 2
Traceback (most recent call last):
  File "convert_to_records_multiCPU.py", line 28, in <module>
    import cv2
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/cv2.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib
Askes-MBP:DareToAGE aske$ `

Kind regards

**Comment by BoyuanJiang** [comment]
There seems some errors about CV2, however, I didn't have ever tested under MAC, so I'm not clear about how to solve it.
