### ISSUE TITLE
waiting during converting to tensoflow records.

### ISSUE THREAD

**Issue by Arthur-Shi** [BoyuanJiang/Age-Gender-Estimate-TF#9]
sudo python convert_to_records_multiCPU.py --imdb --nworks 8
[sudo] password for aries: 
Using imdb dataset
Writing ./data/train/train-000.tfrecords
Writing ./data/train/train-001.tfrecords
Writing ./data/train/train-002.tfrecords
Writing ./data/train/train-003.tfrecords
Writing ./data/train/train-004.tfrecords
Writing ./data/train/train-005.tfrecords
Writing ./data/train/train-006.tfrecords
Writing ./data/train/train-007.tfrecords

I tried python convert_to_records_multiCPU.py --imdb --nworks 32,
but it cannot finish this process too.

What can I do?

**Comment by gmt710** [comment]
@Arthur-Shi ,Hello, Do you remember how to solved this problem ? 
My process also can't stop .
